name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 4092
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
    - uses: actions/checkout@v4
      with:
        submodules: recursive   
    - name: Build the Docker image
      run: ./docker-build.sh Dockerfile

    - name: Run the Docker image
      run: ./docker-run.sh ./my-raspberrypi0-wifi-6.6/yocto-build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: out/poky/build/tmp/deploy/images/raspberrypi0-wifi
